### ISSUE TITLE
Need Boarding Music

### ISSUE THREAD

**Issue by Ralphy444** [Ralphy444/Infinite-Checklist#1]
Will add boarding music in future updates, see the code branch or the .zip file below. Comment below to be assigned to go and grab boarding music. 
[frf.zip](https://github.com/Ralphy444/Infinite-Checklist/files/979161/frf.zip)

**Comment by rohaimkhedr** [comment]
i have found a playlist for AA 
Here’s what’s playing while you board the aircraft:

Chillout
Ice Dream
The XX
Crystalised
Jens Buchert
Hermetic Laws
Phantogram
When I’m Small
Amberland
Obelisk
Lykke Li
I Follow Rivers
Jens Buchert
Dawn Rider
M83
Wait
Here’s what’s playing when you arrive:

Foster the People
I Would Do Anything for You
Hozier
From Eden
Wild Cub
Thunder Clatter
Real Estate
Snow Days
Little Dragon
Ritual Union
Lykke Li
No Rest For The Wicked
Cayucas
Cayucos
Future Islands
Seasons (Waiting on You)
Small Black
No Stranger
Peter Black
Soon
Broken Bells
After the Disco
The Shins
New Slang
Little Joy
The Next Time Around
Ivan & Alyosha
Running For Cover

**Comment by Ralphy444** [comment]
Awesome! Thanks
