### ISSUE TITLE
login screen - BOARDING MUSIC SECTION

### ISSUE THREAD

**Issue by rohaimkhedr** [Ralphy444/Infinite-Checklist#7]
maybe we can make a loginscreen and in your account the following details of you are stored
1. name
2.email
3. maybe a va
you can do then a personal welcome screen maybe it says hello thomas if thomas is logged in to his account

**Comment by Ralphy444** [comment]
This sounds good!, ill try and get round to adding it ;)

**Comment by Ralphy444** [comment]
Will add it in a later update. Too complicated right now.

**Comment by Ralphy444** [comment]
wont work
